#ifndef CONFIG_MODE_CMD_H
#define CONFIG_MODE_CMD_H
//TODO comment

#define N_CONFIG_MODE_CMD 19u

#include <stdint.h>

typedef enum {
	COMBINED,
	ARTICULATED_STEERING,
	TURNTABLE_STEERING,
	SET_POTENTIOMETER_LEFT,
	SET_POTENTIOMETER_RIGHT,
	SET_SERVO_LEFT,
	SET_SERVO_MIDDLE,
	INCREMENT_SERVO,
	DECREMENT_SERVO,
	SET_STEERING_POINT_0,
	SET_STEERING_POINT_1,
	SET_STEERING_POINT_2,
	SET_STEERING_POINT_3,
	SET_STEERING_POINT_4,
	SET_STEERING_POINT_5,
	SET_STEERING_POINT_6,
	SET_AXIS_POINT_0,
	SET_AXIS_POINT_1,
	SET_AXIS_POINT_2,
} config_mode_cmd_t;

uint16_t execute_config_mode_cmd(config_mode_cmd_t command);

#endif //CONFIG_MODE_CMD_H
